# Generated by Django 5.1.5 on 2026-08-12 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('locality', models.CharField(blank=True, max_length=120)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('college_workplace', models.CharField(blank=True, max_length=180)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('interests', models.CharField(blank=True, max_length=500)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=30)),
                ('dietary_preference', models.CharField(choices=[('non_vegetarian', 'Non-Vegetarian'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('halal', 'Halal'), ('keto', 'Keto'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-free')], default='non_vegetarian', max_length=30)),
                ('women_only_mode', models.BooleanField(default=False)),
                ('profile_image_1', models.ImageField(blank=True, null=True, upload_to='profiles/photos/')),
                ('profile_image_2', models.ImageField(blank=True, null=True, upload_to='profiles/photos/')),
                ('profile_image_3', models.ImageField(blank=True, null=True, upload_to='profiles/photos/')),
                ('profile_image_1_blob_key', models.CharField(blank=True, default='', max_length=500)),
                ('profile_image_1_url', models.URLField(blank=True, default='', max_length=1500)),
                ('profile_image_2_blob_key', models.CharField(blank=True, default='', max_length=500)),
                ('profile_image_2_url', models.URLField(blank=True, default='', max_length=1500)),
                ('profile_image_3_blob_key', models.CharField(blank=True, default='', max_length=500)),
                ('profile_image_3_url', models.URLField(blank=True, default='', max_length=1500)),
                ('government_id', models.FileField(blank=True, null=True, upload_to='private/government_ids/')),
                ('government_id_blob_key', models.CharField(blank=True, default='', max_length=500)),
                ('government_id_original_name', models.CharField(blank=True, default='', max_length=255)),
                ('government_id_content_type', models.CharField(blank=True, default='', max_length=100)),
                ('government_id_type', models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('passport', 'Passport'), ('driving_licence', 'Driving Licence'), ('voter_id', 'Voter ID'), ('pan', 'PAN Card'), ('other', 'Other')], max_length=30)),
                ('verification_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_submitted', max_length=30)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
