# Generated by Django 5.1.5 on 2026-08-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_dietary_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dietary_preference',
            field=models.CharField(choices=[('non_vegetarian', 'Non-Vegetarian'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('pescatarian', 'Pescatarian'), ('gluten_free', 'Gluten-free')], default='none', max_length=30),
        ),
    ]
