# Generated by Django 5.1.5 on 2026-08-20 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosevent',
            options={'ordering': ['-activated_at']},
        ),
        migrations.AlterModelOptions(
            name='trustedcontact',
            options={'ordering': ['-created_at']},
        ),
    ]
