# Generated by Django 5.1.5 on 2026-08-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_conversation_conversation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='image_blob_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='image_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='image_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='post',
            name='image_blob_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='image_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='image_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1200),
        ),
        migrations.AddField(
            model_name='post',
            name='video_blob_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='video_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='video_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=1200),
        ),
    ]
